name: Deploy Backend (Render)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ secrets.RENDER_SERVICE_ID != '' && secrets.RENDER_API_KEY != '' }}
    continue-on-error: true
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Triggering Render deployment..."
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H 'Content-Type: application/json' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
            -d '{"clearCache":false}')
          
          http_code=$(echo "$response" | tail -n1)
          if [ "$http_code" -eq 201 ] || [ "$http_code" -eq 200 ]; then
            echo "✅ Render deployment triggered successfully"
          else
            echo "⚠️ Render deployment may have failed (HTTP $http_code)"
            echo "$response" | head -n -1
          fi


