name: E2E

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ secrets.PLAYWRIGHT_BASE_URL != '' && secrets.E2E_EMAIL != '' && secrets.E2E_PASSWORD != '' }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install frontend
        working-directory: frontend
        run: npm ci

      - name: Install Playwright
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run E2E tests
        working-directory: frontend
        env:
          PLAYWRIGHT_BASE_URL: ${{ secrets.PLAYWRIGHT_BASE_URL || 'https://app.ain90.online' }}
          E2E_EMAIL: ${{ secrets.E2E_EMAIL }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
        continue-on-error: true
        run: npm run e2e || echo "E2E tests skipped or failed"

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          retention-days: 7


